In [2]:
from tensorflow.python.keras.datasets import cifar10
(image_train, label_train), (image_test, label_test) = \
                cifar10.load_data()

/home/masaki_endo/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/masaki_endo/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/masaki_endo/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/masaki_endo/anaconda3/env

170500096/170498071 [==============================] - 73s 0us/step


In [4]:
print('img, label for training', image_train.shape, label_train.shape)
print('img, label for test', image_test.shape, label_test.shape)

img, label for training (50000, 32, 32, 3) (50000, 1)
img, label for test (10000, 32, 32, 3) (10000, 1)


In [5]:
image_train = image_train / 255
image_test = image_test / 255

In [8]:
from tensorflow.python.keras.utils import to_categorical
label_train = to_categorical(label_train, 10)
label_test = to_categorical(label_test, 10)

In [1]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Conv2D
from tensorflow.python.keras.layers import MaxPooling2D
from tensorflow.python.keras.layers import Dropout
from tensorflow.python.keras.layers import Flatten
from tensorflow.python.keras.layers import Dense

/home/masaki_endo/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/masaki_endo/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/masaki_endo/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/masaki_endo/anaconda3/env

In [11]:
model = Sequential()

In [15]:
model.add(
    Conv2D(
    filters=32,
    input_shape=(32,32,3),
    kernel_size=(3,3),
    strides=(1,1),
    padding='same',
    activation='relu'
    )
)


model.add(
    Conv2D(
        filters=32,
        kernel_size=(3,3),
        strides=(1,1),
        padding='same',
        activation='relu'
    )
)

model.add(
    MaxPooling2D(
    pool_size=(2,2)
    )
)

model.add(Dropout(0.25))

model.add(
    Conv2D(
        filters=64,
        kernel_size=(3,3),
        strides=(1,1),
        padding='same',
        activation='relu'
    )
)

model.add(
    Conv2D(
        filters=64,
        kernel_size=(3,3),
        strides=(1,1),
        padding='same',
        activation='relu'
    )
)

model.add(
    MaxPooling2D(
     pool_size=(2,2)
    )
)

model.add(Dropout(0.25))

model.add(Flatten())

model.add(
    Dense(
        units=512,
        activation='relu'
    )
)

model.add(Dropout(0.5))

model.add(
    Dense(
        units=10,
        activation='softmax'
    )
)

In [16]:
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 32, 32, 32)        896       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 32, 32, 32)        9248      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 16, 16, 32)        0         
_________________________________________________________________
dropout (Dropout)            (None, 16, 16, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 16, 16, 32)        9248      
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 16, 16, 32)        9248      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 8, 8, 32)          0

In [18]:
CNNmodel1=model.fit(
    image_train,
    label_train,
    batch_size=32,
    epochs=3,
    validation_split = 0.2
)

Train on 40000 samples, validate on 10000 samples
Epoch 1/3
40000/40000 [==============================] - 29s 721us/sample - loss: 1.7150 - acc: 0.3652 - val_loss: 1.3576 - val_acc: 0.4990
Epoch 2/3
40000/40000 [==============================] - 28s 705us/sample - loss: 1.3414 - acc: 0.5119 - val_loss: 1.1890 - val_acc: 0.5763
Epoch 3/3
40000/40000 [==============================] - 28s 702us/sample - loss: 1.1899 - acc: 0.5732 - val_loss: 1.0606 - val_acc: 0.6149


In [19]:
from keras.models import load_model
model.save('myCNN_3epochs.h5')

Using TensorFlow backend.


In [20]:
probs = model.predict(image_test)

In [21]:
probs[0]

array([2.2846308e-04, 2.0949161e-04, 1.1726785e-02, 8.3533865e-01,
       2.5885801e-03, 1.1572691e-01, 2.7571972e-02, 4.5555211e-03,
       1.7325867e-03, 3.2102919e-04], dtype=float32)

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import os
from os import listdir
from keras.preprocessing.image import load_img, img_to_array 

Using TensorFlow backend.


In [3]:
filesU = [filename for filename in listdir('./chapter4_dataset/Directions01_RGB/train/up')
         if not filename.startswith('.')]
filesD = [filename for filename in listdir('./chapter4_dataset/Directions01_RGB/train/down')
         if not filename.startswith('.')]
filesL = [filename for filename in listdir('./chapter4_dataset/Directions01_RGB/train/left')
         if not filename.startswith('.')]
filesR = [filename for filename in listdir('./chapter4_dataset/Directions01_RGB/train/right')
         if not filename.startswith('.')]

In [25]:
print(filesU)

['228.png', '15.png', '0.png', '165.png', '88.png', '234.png', '6.png', '171.png', '191.png', '118.png', '30.png', '46.png', '202.png', '38.png', '101.png', '197.png', '179.png', '223.png', '59.png', '120.png', '226.png', '220.png', '21.png', '27.png', '203.png', '54.png', '188.png', '33.png', '20.png', '123.png', '22.png', '183.png', '44.png', '128.png', '55.png', '90.png', '96.png', '131.png', '141.png', '67.png', '83.png', '11.png', '12.png', '121.png', '91.png', '61.png', '78.png', '180.png', '73.png', '204.png', '224.png', '193.png', '52.png', '116.png', '108.png', '103.png', '35.png', '93.png', '206.png', '65.png', '82.png', '134.png', '122.png', '10.png', '42.png', '140.png', '160.png', '182.png', '3.png', '214.png', '40.png', '25.png', '133.png', '26.png', '31.png', '227.png', '161.png', '146.png', '125.png', '7.png', '211.png', '153.png', '17.png', '181.png', '29.png', '218.png', '1.png', '34.png', '149.png', '207.png', '47.png', '110.png', '167.png', '39.png', '145.png', '163

In [4]:
chestU = np.zeros((len(filesU), 32, 32, 3))
chestD = np.zeros((len(filesD), 32, 32, 3))
chestL = np.zeros((len(filesL), 32, 32, 3))
chestR = np.zeros((len(filesR), 32, 32, 3))

In [5]:
for i in range(len(filesU)):
    fnameform = './chapter4_dataset/Directions01_RGB/train/up/%s'%filesU[i]
    chestU[i] = np.array(img_to_array(load_img(fnameform, target_size=(32,32))))/ 255
    
for i in range(len(filesL)):
    fnameform = './chapter4_dataset/Directions01_RGB/train/left/%s'%filesL[i]
    chestL[i] = np.array(img_to_array(load_img(fnameform, target_size=(32,32))))/255
    
for i in range(len(filesD)):
    fnameform = './chapter4_dataset/Directions01_RGB/train/down/%s'%filesD[i]
    chestD[i] = np.array(img_to_array(load_img(fnameform, target_size=(32,32))))/255
    
for i in range(len(filesR)):
    fnameform = './chapter4_dataset/Directions01_RGB/train/right/%s'%filesR[i]
    chestR[i] = np.array(img_to_array(load_img(fnameform, target_size=(32,32))))/255

In [6]:
print(chestU.shape)

(237, 32, 32, 3)


In [8]:
chestimg_train = np.concatenate((chestU, chestD, chestL, chestR), axis=0)

In [9]:
from tensorflow.python.keras.utils import to_categorical

In [29]:
chestlabelU = np.full((len(filesU), 1), 0, dtype='uint8')
chestlabelD = np.full((len(filesD), 1), 1, dtype='uint8')
chestlabelL = np.full((len(filesL), 1), 2, dtype='uint8')
chestlabelR = np.full((len(filesR), 1), 3, dtype='uint8')

In [30]:
chestlabel_train = np.concatenate((chestlabelU, chestlabelD, 
                                   chestlabelL, chestlabelR), axis=0)
chestonehotlabel_train = to_categorical(chestlabel_train, 4)

In [31]:
chestonehotlabel_train

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]], dtype=float32)

In [13]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Conv2D
from tensorflow.python.keras.layers import MaxPooling2D
from tensorflow.python.keras.layers import Dropout
from tensorflow.python.keras.layers import Flatten
from tensorflow.python.keras.layers import Dense

In [14]:
model = Sequential()

In [18]:
model.add(
    Conv2D(
        filters=32,
        input_shape=(32,32,3),
        kernel_size=(3,3),
        strides=(1,1),
        padding='same',
        activation='relu'
    ) 
)

model.add(
    Conv2D(
        filters=32,
        kernel_size=(3,3),
        strides=(1,1),
        padding='same',
        activation='relu'
    )
)

model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Dropout(0.25))

model.add(
    Conv2D(
        filters=64,
        kernel_size=(3,3),
        strides = (1,1),
        padding='same',
        activation='relu'
    )
)

model.add(
    Conv2D(
        filters=64,
        kernel_size=(3,3),
        strides=(1,1),
        padding='same',
        activation='relu'
    )
)

model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Dropout(0.25))

model.add(Flatten())

model.add(
    Dense(
        units=512, activation='relu'
    )
)

model.add(Dropout(0.5))

model.add(
    Dense(
        units=4, activation='softmax'
    )
)

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 32, 32, 32)        896       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 32, 32, 32)        9248      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 16, 16, 32)        0         
_________________________________________________________________
dropout (Dropout)            (None, 16, 16, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 16, 16, 64)        18496     
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 16, 16, 64)        36928     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 8, 8, 64)          0

In [32]:
model_histry = model.fit(
               chestimg_train,
               chestonehotlabel_train,
               batch_size=32,
               epochs=10,
               validation_split=0.2
             )

Train on 758 samples, validate on 190 samples
Epoch 1/10
758/758 [==============================] - 1s 894us/sample - loss: 15.9018 - acc: 0.3681 - val_loss: 2.2772 - val_acc: 0.0000e+00
Epoch 2/10
758/758 [==============================] - 1s 910us/sample - loss: 0.4444 - acc: 0.8588 - val_loss: 0.3063 - val_acc: 0.9211
Epoch 3/10
758/758 [==============================] - 1s 1ms/sample - loss: 0.0386 - acc: 0.9894 - val_loss: 0.0225 - val_acc: 1.0000
Epoch 4/10
758/758 [==============================] - 1s 1ms/sample - loss: 0.0112 - acc: 0.9974 - val_loss: 4.5682e-04 - val_acc: 1.0000
Epoch 5/10
758/758 [==============================] - 1s 1ms/sample - loss: 0.0030 - acc: 0.9987 - val_loss: 0.0030 - val_acc: 1.0000
Epoch 6/10
758/758 [==============================] - 1s 887us/sample - loss: 0.0022 - acc: 1.0000 - val_loss: 5.0046e-04 - val_acc: 1.0000
Epoch 7/10
758/758 [==============================] - 1s 902us/sample - loss: 6.2587e-04 - acc: 1.0000 - val_loss: 3.2976e-04 - val

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [34]:
results = list(model.predict_classes(chestimg_train, verbose=1))

948/948 [==============================] - 0s 226us/sample


In [35]:
results

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [36]:
cmatrix = confusion_matrix(chestlabel_train, results)

In [37]:
cmatrix

array([[237,   0,   0,   0],
       [  0, 237,   0,   0],
       [  0,   0, 237,   0],
       [  0,   0,   0, 237]])

In [38]:
print(cmatrix)

[[237   0   0   0]
 [  0 237   0   0]
 [  0   0 237   0]
 [  0   0   0 237]]


In [39]:
score = accuracy_score(chestlabel_train, results)
print(score)

1.0


In [40]:
import pandas as pd
import numpy as np
from keras.preprocessing.image import img_to_array, load_img

gsdata = pd.read_csv('./chapter4_dataset/XPAge01_RGB/XP/trainingdata.csv')

In [41]:
gsdata.columns

Index(['filenames', 'age'], dtype='object')

In [46]:
trainingImgdata = np.zeros((len(gsdata['filenames']), 128, 128, 1))

In [48]:
for i in range(len(gsdata['filenames'])):
    fnameform = './chapter4_dataset/XPAge01_RGB/XP/JPGs/%s'%gsdata['filenames'][i]
    trainingImgdata[i] = np.array(img_to_array(load_img(fnameform, grayscale=True, target_size=(128,128)))) / 255
    
trainingImgdata.shape

(80, 128, 128, 1)

In [53]:
trainingGSdata = np.zeros((len(gsdata['age']), 1))

for i in range(len(gsdata['filenames'])):
    trainingGSdata[i][0] = gsdata['age'][i]
    
trainingGSdata.shape

(80, 1)

In [58]:
trainingGS = trainingGSdata.copy()
trainingGS = trainingGS.astype('int')
# 単なる一次元データへ
trainingGS = np.ravel(trainingGS)

trainingGS.shape

(80,)

In [59]:
trainingGS = trainingGS /  100

In [60]:
trainingGS.shape

(80,)

In [61]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Conv2D
from tensorflow.python.keras.layers import MaxPooling2D
from tensorflow.python.keras.layers import Dropout
from tensorflow.python.keras.layers import Flatten
from tensorflow.python.keras.layers import Dense

In [63]:
model = Sequential()

model.add(
    Conv2D(
        filters=32,
        input_shape=(128,128,1),
        kernel_size=(3,3),
        strides=(1,1),
        padding='same',
        activation='relu'
    )
)

model.add(
    Conv2D(
        filters=32,
        kernel_size=(3,3),
        strides=(1,1),
        padding='same',
        activation='relu'
    )
)

model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Dropout(0.25))

model.add(
    Conv2D(
        filters=64,
        kernel_size=(3,3),
        strides=(1,1),
        padding='same',
        activation='relu'
    )
)

model.add(
    Conv2D(
        filters=64,
        kernel_size=(3,3),
        strides=(1,1),
        padding='same',
        activation='relu'
    )
)

model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Dropout(0.25))

model.add(Flatten())

model.add(Dense(units=512, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(units=1, activation='linear'))

model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mse']
)

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 128, 128, 32)      320       
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 128, 128, 32)      9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 64, 64, 32)        0         
_________________________________________________________________
dropout_3 (Dropout)          (None, 64, 64, 32)        0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 64, 64, 64)        18496     
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 64, 64, 64)        36928     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 32, 32, 64)       

In [66]:
hist = model.fit(
    trainingImgdata,
    trainingGS,
    batch_size=8,
    epochs=50,
    validation_split=0.2,
    verbose=1
)

Train on 64 samples, validate on 16 samples
Epoch 1/50
64/64 [==============================] - 1s 20ms/sample - loss: 686.7153 - mean_squared_error: 686.7154 - val_loss: 0.3405 - val_mean_squared_error: 0.3405
Epoch 2/50
64/64 [==============================] - 1s 22ms/sample - loss: 0.6048 - mean_squared_error: 0.6048 - val_loss: 0.1009 - val_mean_squared_error: 0.1009
Epoch 3/50
64/64 [==============================] - 1s 22ms/sample - loss: 0.1025 - mean_squared_error: 0.1025 - val_loss: 0.1718 - val_mean_squared_error: 0.1718
Epoch 4/50
64/64 [==============================] - 1s 20ms/sample - loss: 0.0827 - mean_squared_error: 0.0827 - val_loss: 0.0876 - val_mean_squared_error: 0.0876
Epoch 5/50
64/64 [==============================] - 1s 21ms/sample - loss: 0.0820 - mean_squared_error: 0.0820 - val_loss: 0.0923 - val_mean_squared_error: 0.0923
Epoch 6/50
64/64 [==============================] - 1s 22ms/sample - loss: 0.0903 - mean_squared_error: 0.0903 - val_loss: 0.0878 - val_m